### ISSUE TITLE
Suggestion: Config File

### ISSUE THREAD

**Issue by IdrisQe** [CrimsonDawn45/survival-additions#1]
It would be nice to have a config file where each addition could be enabled or disabled, for example if you wanted to have Flint tools, but not Bone tools or Sandstone tools, but want Netherrack tools but not Nether Quartz tools.

**Comment by StellarWind22** [comment]
Yeah I’ll prolly try to include that in the next update I’ve been busy with other things lately but I’ll prolly try to roll out an update sometime soon

Sent from Mail for Windows 10

From: IdrisQe
Sent: Friday, September 21, 2018 6:13 PM
To: CrimsonDawn45/survival-additions
Cc: Subscribed
Subject: [CrimsonDawn45/survival-additions] Suggestion: Config File (#1)

It would be nice to have a config file where each addition could be enabled or disabled, for example if you wanted to have Flint tools, but not Bone tools or Sandstone tools, but want Netherrack tools but not Nether Quartz tools.
