### ISSUE TITLE
Please use proper versioning.

### ISSUE THREAD

**Issue by K0-RR** [CrimsonDawn45/survival-additions#10]
[main/WARN]: Mod `cdsam` (v1.2.3-Fabric-1.16.5) does not respect SemVer - comparison support is limited.
Please only use two dots (1.2.3) in the version number and don't add mc version, loader information, and "v" to it.

**Comment by StellarWind22** [comment]
sorry I had it working earlier my build settings just got messed up and included that information in the mod version itself instead of just the .jar name

**Comment by StellarWind22** [comment]
I'll be fixing this along with a couple of bugs in 1.2.4 which will probably come out sometime tomorrow

**Comment by StellarWind22** [comment]
This is fixed as of 1.2.4 it was because I accidentally added 'v' into the version info.
