### ISSUE TITLE
[Bug] Pickaxes are broke

### ISSUE THREAD

**Issue by ZaneDragonBorn** [CrimsonDawn45/survival-additions#11]
Seems like pickaxes are just as good as swords. They aren't even good enough to break smooth stone. I think you may have classified them as a Sword or something because they aren't made to break Blocks.

MC Version: 1.16.4
Fabric Version: 0.11.1
Mod Version: 1.2.2

**Comment by StellarWind22** [comment]
Yeah in the currently released version I accidentally marked all the pickaxes as axes I just haven't had time lately to work on the mod that much this last week. I'm working on fixing right now

**Comment by StellarWind22** [comment]
This bug has been fixed as of version 1.2.4
