### ISSUE TITLE
crash on startup version 1.3 1.16.5

### ISSUE THREAD

**Issue by Lordbaane** [CrimsonDawn45/survival-additions#13]
---- Minecraft Crash Report ----
// You're mean.

Time: 09/02/21 12:04 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cdsam'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: me/crimsondawn45/fabricshieldlib/lib/object/FabricShield
	at me.crimsondawn45.cdsam.Main.onInitialize(Main.java:32)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.ClassNotFoundException: me.crimsondawn45.fabricshieldlib.lib.object.FabricShield
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.UnsafeKnotClassLoader.loadClass(UnsafeKnotClassLoader.java:50)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3489672384 bytes (3328 MB) / 5359271936 bytes (5111 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8192m
	Fabric Mods: 
		adabraniummod: Adabranium 1.3.2+1.16.5
		adapaxels: AdaPaxels 1.0.6+1.16.5
		alaskanativecraft: Alaska Native Craft 1.1.0
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		battletowers: Battle Towers 3.3.2-1.16.4
		betterbeds: Better Beds 1.1.0
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		biomemakeover: Biome Makeover 1.16.4-1.2.11
		blame: Blame 1.16.4-2.4.1
		blockus: Blockus 2.0.2+1.16.4
		bowinfinityfix: Bow Infinity Fix rv9
		campanion: Campanion 1.3.3
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cavebiomes: Cave Biomes 0.6.2
		cdsam: Survival Additions 1.3.0-Fabric-1.16.5
		ce_foodstuffs: Common Expansion: Foodstuffs 1.1.3
		chainmail: Chainmail 0.5.0
		cinderscapes: Cinderscapes 1.3.3
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		commonformatting: common formatting 1.0.1
		cpas: conveniently placed armor slots 1.3.0+1.16.5
		croptopia: Croptopia 1.2.0
		crowdin-translate: CrowdinTranslate 1.2
		customportalapi: customportalapi 0.0.1-beta20-1.16
		dawn: Dawn API 1.6.5
		dt: Damage Threshold 1.3
		dynamicentry: dynamic entry 0.1.3
		earthtojavamobs: Earth2Java 1.6.1+1.16.4
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.3
		economical_villager_trading: Economical Villager Trading 1.0.3+MC1.16.4-1.16.5
		emerald_tools: Emerald Tools 1.1.2
		enchant_giver: Enchant Giver 1.0.3
		enchantedbookredesign: Enchanted Book Redesign 1.1
		enchantment_lore: EnchantmentLore 1.1.1+MC1.16.1-1.16.5
		expandedstorage: ExpandedStorage 5.6.32
		expcontainer: Experience Container [XP] 1.12
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricasmtools: Fabric ASM tools 0.3.2
		fabrication: Fabrication 1.3.0
		fabricloader: Fabric Loader 0.11.1
		falling_tree: FallingTree 2.10.0
		fiber: fiber 0.23.0-2
		go-fish: Go Fish 1.2.1-beta-1.16.4
		gobber2: Gobber2 2.3.67
		goldenhoppers: Golden Hoppers 1.0.1
		gravel-ores: Gravel Ores 1.2.0+1.16.2
		grossfabrichacks: GrossFabricHacks 1.0.3
		here-be-no-dragons: Here be no Dragons! 1.0.0
		homecamp: Home Camp 1.0.3
		illuminations: Illuminations 1.4.5
		imm_ptl_core: Immersive Portals Core 0.68
		immersive_portals: Immersive Portals 0.68
		inventory_control_tweaks: Inventory Control Tweaks 1.2.4+MC1.16.2-1.16.5
		inventoryhud: Inventory HUD + 3.2.0
		ironfurnaces: Iron Furnaces 2.4.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kiln: Kiln 1.1.0+1.16.5
		launchersmod: Launchers 3.2.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		libstructure: LibStructure 1.5
		lightstones: Lightstones 1.3.0
		limitless: limitless 1.1.2
		lithium: Lithium 0.6.3
		logical_zoom: Logical Zoom 0.0.8
		magic_lanterns: Magic Lanterns 1.1.0
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		mcda: MC Dungeons Armors 1.1.2
		mcdw: MC Dungeons Weapons 2.7.1
		minecraft: Minecraft 1.16.5
		mo_glass: Mo Glass 1.5-MC1.16.5
		modmenu: Mod Menu 1.16.6
		more_gems: More Gems 1.1.22
		morepaintings: More Paintings 1.0.4
		morerecipes: morerecipes 2.0.0
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		multishot: Multishot Infinity 1.1.0
		net_bytebuddy_byte-buddy-agent: byte-buddy-agent 1.10.19
		net_gudenau_lib_unsafe: unsafe 1.4.1
		nookbuild: NookBuild 1.4.0
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		overpowered_mending: Overpowered Mending 2.2.3
		pandamc_concreteplus: Concrete plus 1.5.2
		patchouli: Patchouli 1.16.4-48-FABRIC
		phormat: phormat 1.0.0
		phosphor: Phosphor 0.7.0+build.10
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.9-1.16.5
		pugh_lib: Pugh Lib 1.1.0
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		resourceful_tools: Resourceful Tools 1.0.53
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.9.171
		roughlyenoughitems-api: REI (API) 5.9.171
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.9.171
		roughlyenoughitems-runtime: REI (Runtime) 5.9.171
		rpgstats: RPGStats 3.1.1+1.16.4
		shelf: Shelf 1.1.1
		simple_backpack: SimpleBackpack 1.0.38
		simpleangelring: Simple Angel Ring 1.0.1+1.16
		somnus: Somnus API 0.0.10-1.16.4
		spellbound: Spellbound 1.1.3
		starry_sky: Starry Skies 1.0.8-1.16.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		sturdygold: sturdy gold 0.1.0
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		trampledisablerfabric: Trample Disabler 1.0.0
		traverse: Traverse 3.3.1
		tweakeroo: Tweakeroo 0.10.0-dev.20210209.145902
		tweed: Tweed API 3.0.0-beta.22
		user11681_reflect: reflect 1.2.0
		user11681_shortcode: shortcode 0.4.0
		vanguard: Vanguard 1.0.5
		veinmining: Vein Mining 0.0.6-1.16.5
		voyager: Voyager 1.0.0
		wild_explorer: Wild Explorer 1.3.2
		wthit: wthit 2.2.0+1.16.5
		xaerominimap: Xaero's Minimap 21.3.0
		xaeroworldmap: Xaero's World Map 1.12.0
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Lordbaane** [comment]
Added and remove the 5 mods I updated and the crashes stopped when this mod was removed.

**Comment by Lordbaane** [comment]
Reverted to 1.2.3 version and no issues.

**Comment by StellarWind22** [comment]
Yeah, that's because 1.3.0 requires fabric shield lib I forgot to properly add it to the dependency list so it will crash without it and it doesn't tell you that it needs it. I'm probably going to put out a 1.3.1 patch to fix this.

**Comment by StellarWind22** [comment]
Yeah, fabric shield lib also appears to be very broken. I really wanted to add shields back into the mod because they were in the original 1.12 forge version, but it seems like making that work is very difficult. I might have to just remove the shields again.

**Comment by StellarWind22** [comment]
This should be fixed as the dependency is completely removed in 1.3.2 due to fabric shield lib having so many bugs.
