### ISSUE TITLE
Please update to MC 1.17

### ISSUE THREAD

**Issue by Artellia** [CrimsonDawn45/survival-additions#15]
Please update to MC 1.17

**Comment by StellarWind22** [comment]
Sorry, but I have completely lost interest in Minecraft I and Idk why kept making promises to update it on the mod pages. This will probably never be updated to 1.17 unless you do it yourself.

**Comment by Artellia** [comment]
That's sad to hear. This is one of the only options to replace wood tools with a primitive themed early game progression. I hope you find a capable modder to take over your projects.
