### ISSUE TITLE
Terracotta tools uncraftable

### ISSUE THREAD

**Issue by IdrisQe** [CrimsonDawn45/survival-additions#3]
Hi, me again. So in testing my modpack, I found that while you can smelt the Terracotta heads for tools, you can't use them to craft the actual teracotta tools in the current release. This could possibly be a mod conflict on my end, but I don't really think anything I have would cause that.

**Comment by StellarWind22** [comment]
oh sorry if your using the copy from github I kind of accedentally deleted the recipe files for it on the current commit and I mostly use github as a backup if my computer dies so the copy on it isnt really a full realease most of the time

**Comment by IdrisQe** [comment]
I'm not actually using the github version, I'm using the latest from Curseforge, so I'm not sure what's going on there.

**Comment by StellarWind22** [comment]
well oops lol guess that problem has been around longer than I thought

**Comment by StellarWind22** [comment]
guess there's gonna be a update soon
