### ISSUE TITLE
Edible Tools - Fabric 1.2.1

### ISSUE THREAD

**Issue by garyhopple** [CrimsonDawn45/survival-additions#7]
in SurvivalAdditions-v1.2.1-fabric-MC1.16.4.jar, almost every single item (INCLUDING TOOLS, WEAPONS, AND KNAPPED FLINT) are edible. 

PleaseFixThisAsThisIsOverlyCursed.

**Comment by StellarWind22** [comment]
That is really really weird let me see if I can figure out what is going on???

**Comment by StellarWind22** [comment]
Yeah, I just found where the bug is I'm gonna have to do another release to patch it :(

**Comment by StellarWind22** [comment]
Yeah, thanks for reporting! I fixed that bug and another bug I hadn't noticed before the last release I should have v1.2.2 out very very soon!
