### ISSUE TITLE
Compat with Tiered mod.

### ISSUE THREAD

**Issue by K0-RR** [CrimsonDawn45/survival-additions#9]
Can You add support for [Tiered](https://www.curseforge.com/minecraft/mc-mods/tiered) mod? Mod [GitHub](https://github.com/Draylar/tiered).
This mod gives tools, armor, and weapons random qualities when they enter your inventory, inspired by Terraria tools. All the qualities, as well as the tools that can get them, are completely configurable.
![image](https://user-images.githubusercontent.com/43277609/101697272-ce348600-3a77-11eb-9bfa-03d5a2913954.png)

Seems like You would need to do this - "Mods need to add their tools to the respective tags inside the fabric namespace (fabric:pickaxes, fabric:chestplates, fabric:shovels, etc.)" - https://github.com/Draylar/tiered/issues/12

**Comment by StellarWind22** [comment]
I'll see about adding support for this mod, I should probably have my tools in that namespace in the first place because it's likely other mods might do something similar.

**Comment by StellarWind22** [comment]
Yeah, so this feature has been added as of v1.2.3. Tiered hasn't been updated to 1.16.5 yet(at least I'm not sure if the current version works on it), but I did test it with the 1.15 version, and it all working I went ahead and added the tools into the correct tags in all supported versions of Survival Additions so if the mod is backported to 1.14.4 it should work.
